In [17]:
!pip3 install torch
!python3 -V

Defaulting to user installation because normal site-packages is not writeable
You should consider upgrading via the '/Library/Developer/CommandLineTools/usr/bin/python3 -m pip install --upgrade pip' command.
Python 3.9.6


In [20]:
import torch
x = torch.tensor([[1,2]])
y = torch.tensor([[1],[2]])
print(y)

print(x.shape)
print(y.shape)
print(x.dtype)

tensor([[1],
        [2]])
torch.Size([1, 2])
torch.Size([2, 1])
torch.int64


In [6]:
x = torch.tensor([False,1,2.0])
print(x)

tensor([0., 1., 2.])


In [7]:
#random with full 0
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [8]:
#random with full ones
torch.ones(4,3)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [10]:
torch.randint(0,10,(3,4))

tensor([[7, 0, 5, 4],
        [6, 2, 3, 7],
        [5, 7, 5, 3]])

In [13]:
#random between 0 and 1
torch.rand(3,4)

tensor([[0.8587, 0.1567, 0.8064, 0.5666],
        [0.5120, 0.2764, 0.2786, 0.4944],
        [0.4810, 0.0048, 0.7108, 0.4016]])

In [12]:
#random number in normal distribution
torch.randn((3,4))

tensor([[-0.8741,  0.9960,  0.3081, -2.6579],
        [ 1.3631, -0.6549,  0.6804, -0.6663],
        [-0.5870, -0.1721,  0.2224,  0.7374]])

In [23]:
import numpy as np
x = np.array([[1,2,3],[3,4,5]])
y = torch.tensor(x)
print(type(y))

<class 'torch.Tensor'>
