In [9]:
!pip3 install torch
!python3 -V

Defaulting to user installation because normal site-packages is not writeable
You should consider upgrading via the '/Library/Developer/CommandLineTools/usr/bin/python3 -m pip install --upgrade pip' command.
Python 3.9.6


In [8]:
import torch
x = torch.tensor([[1,2]])
y = torch.tensor([[1],[2]])
print(y)

print(x.shape)
print(y.shape)
print(x.dtype)

tensor([[1],
        [2]])
torch.Size([1, 2])
torch.Size([2, 1])
torch.int64


In [5]:
x = torch.tensor([False,1,2.0])
print(x)

tensor([0., 1., 2.])


In [6]:
#random with full 0
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [8]:
#random with full ones
torch.ones(4,3)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [10]:
torch.randint(0,10,(3,4))

tensor([[7, 0, 5, 4],
        [6, 2, 3, 7],
        [5, 7, 5, 3]])

In [13]:
#random between 0 and 1
torch.rand(3,4)

tensor([[0.8587, 0.1567, 0.8064, 0.5666],
        [0.5120, 0.2764, 0.2786, 0.4944],
        [0.4810, 0.0048, 0.7108, 0.4016]])

In [12]:
#random number in normal distribution
torch.randn((3,4))

tensor([[-0.8741,  0.9960,  0.3081, -2.6579],
        [ 1.3631, -0.6549,  0.6804, -0.6663],
        [-0.5870, -0.1721,  0.2224,  0.7374]])

In [7]:
import numpy as np
x = np.array([[1,2,3],[3,4,5]])
y = torch.tensor(x)
print(type(y))

<class 'torch.Tensor'>


In [2]:
!pip3 install torchvision

Defaulting to user installation because normal site-packages is not writeable
     |████████████████████████████████| 1.6 MB 1.6 MB/s eta 0:00:01
You should consider upgrading via the '/Library/Developer/CommandLineTools/usr/bin/python3 -m pip install --upgrade pip' command.


In [2]:
import torch
from torch import nn
from torch.utils.data import TensorDataset, Dataset, DataLoader
from torch.optim import Adam, SGD

In [3]:
device = 'cpu'
from torchvision import datasets
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

In [15]:
X_train = torch.tensor([[[[1,2,3,4],[2,3,4,5], 
                       [5,6,7,8],[1,3,4,5]]],        
                     [[[-1,2,3,-4],[2,-3,4,5],          
                          [-5,6,-7,8],[-1,-3,-4,-5]]]]).to(device).float()
X_train /= 8
y_train = torch.tensor([0,1]).to(device).float()
print(X_train.shape)


torch.Size([2, 1, 4, 4])


In [9]:
model = nn.Sequential(
    nn.Conv2d(1,1,kernel_size=3),
    nn.MaxPool2d(kernel_size=2),
    nn.ReLU(),
    nn.Flatten(),
    nn.Linear(1,1),
    nn.Sigmoid()
)
loss = nn.BCELoss()
optimizer = Adam(model.parameters(),lr = 1e-3)


In [12]:
%pip install torch_summary

Defaulting to user installation because normal site-packages is not writeable
You should consider upgrading via the '/Library/Developer/CommandLineTools/usr/bin/python3 -m pip install --upgrade pip' command.
Note: you may need to restart the kernel to use updated packages.


In [14]:
from torchsummary import summary
summary(model, X_train)

Layer (type:depth-idx)                   Output Shape              Param #
├─Conv2d: 1-1                            [-1, 1, 2, 2]             10
├─MaxPool2d: 1-2                         [-1, 1, 1, 1]             --
├─ReLU: 1-3                              [-1, 1, 1, 1]             --
├─Flatten: 1-4                           [-1, 1]                   --
├─Linear: 1-5                            [-1, 1]                   2
├─Sigmoid: 1-6                           [-1, 1]                   --
Total params: 12
Trainable params: 12
Non-trainable params: 0
Total mult-adds (M): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00


Layer (type:depth-idx)                   Output Shape              Param #
├─Conv2d: 1-1                            [-1, 1, 2, 2]             10
├─MaxPool2d: 1-2                         [-1, 1, 1, 1]             --
├─ReLU: 1-3                              [-1, 1, 1, 1]             --
├─Flatten: 1-4                           [-1, 1]                   --
├─Linear: 1-5                            [-1, 1]                   2
├─Sigmoid: 1-6                           [-1, 1]                   --
Total params: 12
Trainable params: 12
Non-trainable params: 0
Total mult-adds (M): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00